version: '1.0'
stages:
  - prepare
  - test
  - build
  - 'integration test'
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'Himanshurock/spring-boot-2-sample-app-master'
    revision: master
    git: github
  run_unit_tests:
    title: Compile/Unit test
    stage: test
    image: 'maven:3.5.2-jdk-8-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository test      
  build_app_image:
    title: Building Docker Image
    type: build
    stage: build
    image_name: spring-boot-2-sample-app
    working_directory: ./
    tag: 'multi-stage'
    dockerfile: Dockerfile
  run_integration_tests:
    title: Integration test
    stage: 'integration test'
    image: maven:3.5.2-jdk-8-alpine
    environment:
      - MONGO_PORT=27017
    commands:
     - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository integration-test
    services:
      composition:
       mongo:
          image: mongo:latest
          ports:
            - 27017
      readiness:
        timeoutSeconds: 30
        periodSeconds: 15
        image: '${{build_app_image}}'
        commands:
          - "nslookup mongo"
          - "nc -z mongo 27017"
